set(_TGSTK_ITERS_TREE_SOURCE_FILES_CPP
    tree_comms.cpp
    BTree/btree.cpp
)

set(TGSTK_ITERS_TREE_SOURCE_FILES_CPP )
add_head_foreach(TGSTK_ITERS_TREE_SOURCE_FILES_CPP "tree" ${_TGSTK_ITERS_TREE_SOURCE_FILES_CPP})