set(_TGSTK_ITERS_TREE_HEADER_FILES_H
    tree_comms.h
    btree.h
)

set(TGSTK_ITERS_TREE_HEADER_FILES_H )
add_head_foreach(TGSTK_ITERS_TREE_HEADER_FILES_H "tree" ${_TGSTK_ITERS_TREE_HEADER_FILES_H})